version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.1-jdk

    working_directory: ~/phaili2021_as3

    steps:
      - checkout

      - run: mvn clean package

      - run: mvn clean compile jib:build -Djib.to.auth.username=$DOCKER_USER -Djib.to.auth.password=$DOCKER_PASS -Dimage=phajili/phajili2021_as3:$CIRCLE_BUILD_NUM

